### ISSUE TITLE
Week 8 ready for review

### ISSUE THREAD

**Issue by jonesna213** [jonesna213/Week-8-Exercise#1]
@pawaitemadisoncollege week 8 is complete.

- key takeaway was getting experience using an API in java and being able to use/access the data
- it wasn't really that challenging (just a little tedious with the url)
- I ran into the problem of having multiple classes generated when I did the generate pojo. Then realized there was another video where you talked about the multiple classes. I usually leave the supplementary video till after doing the exercise unless there needed like with this week.

**Comment by pawaitemadisoncollege** [comment]
Hi @jonesna213 - yes! Those multiple-class apis can be challenging. Maybe I should remove the "supplemental" status of that video! 

Regarding the 404s you experienced on ids other than 6. It's interesting that the service owners leave the api pretty open - anyone can delete a record, from what I recall. I _assume_ they  reset the data on a scheduled basis - you must have hit it just right (or just wrong) that so many records were missing. 

- [ ] In a "real" implementation it may be a good idea to externalize the base url in a properties file to make this easy to update without doing a source code change. https://github.com/jonesna213/Week-8-Exercise/blob/1632aea77d3ef3c964d10aced3554753b9e42bc2/src/main/java/edu/matc/persistence/SwaggerDao.java#L26.
